/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 */

export type EncodingStyle = (typeof EncodingStyle)[keyof typeof EncodingStyle]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EncodingStyle = {
  form: 'form',
  spaceDelimited: 'spaceDelimited',
  pipeDelimited: 'pipeDelimited',
  deepObject: 'deepObject',
} as const
