/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 */
import type { SpecificationExtensions } from './specificationExtensions'
import type { StylesForForm } from './stylesForForm'
import type { EncodingHeaders } from './encodingHeaders'
import type { EncodingStyle } from './encodingStyle'

export type Encoding = SpecificationExtensions &
  StylesForForm & {
    allowReserved?: boolean
    contentType?: string
    explode?: boolean
    headers?: EncodingHeaders
    style?: EncodingStyle
  }
