/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 */
import type { ExamplesExamples } from './examplesExamples'

export interface Examples {
  example?: unknown
  examples?: ExamplesExamples
}
