/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 */
import type { SpecificationExtensions } from './specificationExtensions'

/**
 * The description of OpenAPI v3.1.x Documents without Schema Object validation
 */
export type Petstore = SpecificationExtensions
