/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 */
import type { SpecificationExtensions } from './specificationExtensions'
import type { TypeApikey } from './typeApikey'
import type { TypeHttp } from './typeHttp'
import type { TypeHttpBearer } from './typeHttpBearer'
import type { TypeOauth2 } from './typeOauth2'
import type { TypeOidc } from './typeOidc'
import type { SecuritySchemeType } from './securitySchemeType'

export type SecurityScheme = SpecificationExtensions &
  TypeApikey &
  TypeHttp &
  TypeHttpBearer &
  TypeOauth2 &
  TypeOidc & {
    description?: string
    type: SecuritySchemeType
  }
