/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 */

export type SecuritySchemeType =
  (typeof SecuritySchemeType)[keyof typeof SecuritySchemeType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SecuritySchemeType = {
  apiKey: 'apiKey',
  http: 'http',
  mutualTLS: 'mutualTLS',
  oauth2: 'oauth2',
  openIdConnect: 'openIdConnect',
} as const
